
/*
WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

This file was generated from .idl using "rtiddsgen".
The rtiddsgen tool is part of the RTI Connext distribution.
For more information, type 'rtiddsgen -help' at a command shell
or consult the RTI Connext manual.
*/

package rti.dds.monitoring;

import com.rti.dds.cdr.CdrEncapsulation;
import com.rti.dds.cdr.CdrInputStream;
import com.rti.dds.cdr.CdrOutputStream;
import com.rti.dds.cdr.CdrPrimitiveType;
import com.rti.dds.cdr.CdrBuffer;
import com.rti.dds.cdr.CdrHelper;
import com.rti.dds.cdr.CdrMemberInfo;
import com.rti.dds.domain.DomainParticipant;
import com.rti.dds.publication.DataWriter;
import com.rti.dds.publication.DataWriterListener;
import com.rti.dds.subscription.DataReader;
import com.rti.dds.subscription.DataReaderListener;
import com.rti.dds.topic.KeyHash_t;
import com.rti.dds.topic.TypeSupportImpl;
import com.rti.dds.topic.TypeSupportType;
import com.rti.dds.util.Sequence;
import com.rti.dds.topic.DefaultEndpointData;
import com.rti.dds.infrastructure.RETCODE_ERROR;

import com.rti.dds.infrastructure.*;
import com.rti.dds.topic.TypeSupportParticipantInfo;
import com.rti.dds.topic.TypeSupportEndpointInfo;
import com.rti.dds.typecode.TypeCode;
import com.rti.dds.cdr.IllegalCdrStateException;

import com.rti.dds.infrastructure.Copyable;

/**
* A collection of useful methods for dealing with objects of type
* DomainParticipantEntityStatistics
*/

public class DomainParticipantEntityStatisticsTypeSupport extends TypeSupportImpl {
    // -----------------------------------------------------------------------
    // Private Fields
    // -----------------------------------------------------------------------

    private static final String TYPE_NAME = "rti::dds::monitoring::DomainParticipantEntityStatistics";

    private static final char[] PLUGIN_VERSION = {2, 0, 0, 0};     
    private static final DomainParticipantEntityStatisticsTypeSupport _singleton
    = new DomainParticipantEntityStatisticsTypeSupport();

    // -----------------------------------------------------------------------
    // Public Methods
    // -----------------------------------------------------------------------

    // --- External methods: -------------------------------------------------
    /* The methods in this section are for use by users of RTI Connext
    */

    public static String get_type_name() {
        return _singleton.get_type_nameI();
    }

    public static void register_type(DomainParticipant participant,
    String type_name) {
        _singleton.register_typeI(participant, type_name);
    }

    public static void unregister_type(DomainParticipant participant,
    String type_name) {
        _singleton.unregister_typeI(participant, type_name);
    }

    /* The methods in this section are for use by RTI Connext
    * itself and by the code generated by rtiddsgen for other types.
    * They should be used directly or modified only by advanced users and are
    * subject to change in future versions of RTI Connext.
    */
    public static DomainParticipantEntityStatisticsTypeSupport get_instance() {
        return _singleton;
    }

    public static DomainParticipantEntityStatisticsTypeSupport getInstance() {
        return get_instance();
    }

    public static TypeCode getTypeCode(){
        return DomainParticipantEntityStatisticsTypeCode.VALUE;
    }

    public Object create_data() {
        return DomainParticipantEntityStatistics.create();
    }

    public void destroy_data(Object data) {
        return;
    }
    public Object create_key() {
        return new DomainParticipantEntityStatistics();
    }

    public void destroy_key(Object key) {
        return;
    }
    public Class get_type() {
        return DomainParticipantEntityStatistics.class;
    }

    /**
    * This is a concrete implementation of this method inherited from the base class.
    * This method will perform a deep copy of <code>source</code> into
    * <code>destination</code>.
    * 
    * @param src The Object which contains the data to be copied.
    * @return Returns <code>destination</code>.
    * @exception NullPointerException If <code>destination</code> or 
    * <code>source</code> is null.
    * @exception ClassCastException If either <code>destination</code> or
    * <code>this</code> is not a <code>DomainParticipantEntityStatistics</code>
    * type.
    */
    public Object copy_data(Object destination, Object source) {

        DomainParticipantEntityStatistics typedDst = (DomainParticipantEntityStatistics) destination;
        DomainParticipantEntityStatistics typedSrc = (DomainParticipantEntityStatistics) source;

        return typedDst.copy_from(typedSrc);

    }

    public long get_serialized_sample_max_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.Duration_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;
    }

    public long get_serialized_sample_min_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {

        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.Duration_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(0 );

        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;

    }

    public long get_serialized_sample_size(
        Object endpoint_data, boolean include_encapsulation, 
        short encapsulation_id, long currentAlignment,
        Object sample) 
    {
        DomainParticipantEntityStatistics typedSrc = (DomainParticipantEntityStatistics) sample;
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.participant_key);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.Duration_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.period);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.process);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(0);
        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);

        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return currentAlignment - origAlignment;
    }

    public long get_serialized_key_max_size(
        Object endpoint_data,
        boolean include_encapsulation, 
        short encapsulation_id,
        long currentAlignment) 
    {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().get_serialized_key_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.Duration_tTypeSupport.get_instance().get_serialized_key_max_size(endpoint_data,false, encapsulation_id,0);
        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) +
        2*CdrPrimitiveType.SHORT.size +
        2*CdrPrimitiveType.INT.size);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }

        return currentAlignment - origAlignment;
    }

    public void serialize(Object endpoint_data,Object src, CdrOutputStream dst,boolean serialize_encapsulation,
    short encapsulation_id, boolean serialize_sample, Object endpoint_plugin_qos) {
        int position = 0;
        long memberId = 0;
        int memberLengthPosition = 0;
        boolean skipListEndId_tmp = false;
        long maxLength = 0;

        if (!dst.isDirty()) {
            dst.setDirtyBit(true);

            try{
                maxLength = get_serialized_sample_max_size(endpoint_data, false, encapsulation_id,0);
            } catch (ArithmeticException ex) {
                maxLength =  MAX_SAMPLE_SIZE;
            }

            if (maxLength > 65535) {
                dst.useExtendedMemberId = true;
            }
            else{
                dst.useExtendedMemberId = false;
            }
        }

        skipListEndId_tmp =  dst.skipListEndId;
        dst.skipListEndId = false;

        if(serialize_encapsulation) {
            if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_BE;
            } else if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_LE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_LE;
            }

            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();

        }

        if(serialize_sample) {

            DomainParticipantEntityStatistics typedSrc = (DomainParticipantEntityStatistics) src;

            memberId = 0;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.participant_key, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 1;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.Duration_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.period, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 2;
            memberLengthPosition = dst.writeMemberId((short)memberId);
            dst.writeInt(typedSrc.domain_id);
            dst.writeMemberLength(memberLengthPosition, false);

            memberId = 3;
            memberLengthPosition = dst.writeMemberId((short)memberId);
            dst.writeInt(typedSrc.host_id);
            dst.writeMemberLength(memberLengthPosition, false);

            memberId = 4;
            memberLengthPosition = dst.writeMemberId((short)memberId);
            dst.writeInt(typedSrc.process_id);
            dst.writeMemberLength(memberLengthPosition, false);

            memberId = 5;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().serialize(endpoint_data, typedSrc.process, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 6;
            memberLengthPosition = dst.writeMemberId((short)memberId);
            dst.writeInt(typedSrc.remoteParticipantCount);
            dst.writeMemberLength(memberLengthPosition, false);

            memberId = 7;
            memberLengthPosition = dst.writeMemberId((short)memberId);
            dst.writeInt(typedSrc.remoteWriterCount);
            dst.writeMemberLength(memberLengthPosition, false);

            memberId = 8;
            memberLengthPosition = dst.writeMemberId((short)memberId);
            dst.writeInt(typedSrc.remoteReaderCount);
            dst.writeMemberLength(memberLengthPosition, false);
            if (!(skipListEndId_tmp)) {
                boolean mustUnderstand=false; /*Not default. Explicity set for backward compatibility*/
                memberLengthPosition = 
                dst.writeMemberId(
                    (short)CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END, mustUnderstand);
                dst.writeMemberLength(memberLengthPosition, false);
            }
            dst.skipListEndId = skipListEndId_tmp;

        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }

    }
    public long serialize_to_cdr_buffer(
        byte[] buffer,
        long length,
        DomainParticipantEntityStatistics src)
    {
        return super.serialize_to_cdr_buffer(buffer,length,src);
    }

    public void serialize_key(
        Object endpoint_data,
        Object src,
        CdrOutputStream dst,
        boolean serialize_encapsulation,
        short encapsulation_id,
        boolean serialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        boolean skipListEndId_tmp = false;
        long maxLength = 0;

        if (!dst.isDirty()) {
            dst.setDirtyBit(true);

            try{
                maxLength = get_serialized_sample_max_size(endpoint_data, false, encapsulation_id,0);
            } catch (ArithmeticException ex) {
                maxLength =  MAX_SAMPLE_SIZE;
            }

            if (maxLength > 65535) {
                dst.useExtendedMemberId = true;
            }
            else{
                dst.useExtendedMemberId = false;
            }
        }

        skipListEndId_tmp =  dst.skipListEndId;
        dst.skipListEndId = false;

        if (serialize_encapsulation) {
            if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_BE;
            } else if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_LE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_LE;
            }

            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();
        }

        if (serialize_key) {

            DomainParticipantEntityStatistics typedSrc = (DomainParticipantEntityStatistics) src;    
            dst.skipListEndId = false;
            {
                int memberId = 0;
                long memberLength = 0;
                int memberLengthPosition = 0;
                int position_tmp = 0;

                memberId = 0;
                memberLengthPosition = dst.writeMemberId((short)memberId);
                DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().serialize_key(endpoint_data, typedSrc.participant_key, dst, false, encapsulation_id,true,endpoint_plugin_qos);
                dst.writeMemberLength(memberLengthPosition, false);
                memberId = 1;
                memberLengthPosition = dst.writeMemberId((short)memberId);
                DDSMonitoring.Duration_tTypeSupport.get_instance().serialize_key(endpoint_data, typedSrc.period, dst, false, encapsulation_id,true,endpoint_plugin_qos);
                dst.writeMemberLength(memberLengthPosition, false);
                if (!(skipListEndId_tmp)) {
                    boolean mustUnderstand=false; /*Not default. Explicity set for backward compatibility*/
                    memberLengthPosition = 
                    dst.writeMemberId(
                        (short)CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END, mustUnderstand);
                    dst.writeMemberLength(memberLengthPosition, false);
                }
                dst.skipListEndId = skipListEndId_tmp;

            }

        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }
    }

    public Object deserialize_sample(
        Object endpoint_data,
        Object dst, 
        CdrInputStream src, boolean deserialize_encapsulation,
        boolean deserialize_sample,
        Object endpoint_plugin_qos) 
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_sample) {

            DomainParticipantEntityStatistics typedDst = (DomainParticipantEntityStatistics) dst;
            typedDst.clear();      
            while (end != true && src.available() > 0) {

                memberInfo = src.readMemberInfo();
                tmpPosition = src.getBuffer().currentPosition();
                tmpSize = src.getBuffer().getSize(); 
                tmpLength = memberInfo.length;
                src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));

                switch (memberInfo.memberId) {

                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                    break; 

                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                    end = true;
                    break;
                    case 0:
                    typedDst.participant_key = (DDSMonitoring.BuiltinTopicKey_t)DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.participant_key, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 1:
                    typedDst.period = (DDSMonitoring.Duration_t)DDSMonitoring.Duration_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.period, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 2:
                    typedDst.domain_id = src.readInt();
                    break;
                    case 3:
                    typedDst.host_id = src.readInt();
                    break;
                    case 4:
                    typedDst.process_id = src.readInt();
                    break;
                    case 5:
                    typedDst.process = (rti.dds.monitoring.ProcessStatistics)rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.process, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 6:
                    typedDst.remoteParticipantCount = src.readInt();
                    break;
                    case 7:
                    typedDst.remoteWriterCount = src.readInt();
                    break;
                    case 8:
                    typedDst.remoteReaderCount = src.readInt();
                    break;
                    default:
                    if (memberInfo.flagMustUnderstand) {
                        throw new RETCODE_ERROR(
                            "unknown member ID "+ 
                            memberInfo.memberId);
                    } break;
                }             
                src.getBuffer().setDesBufferSize(tmpSize);
                src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

            }
        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void deserialize_from_cdr_buffer(
        DomainParticipantEntityStatistics dst,
        byte[] buffer,
        long length) 
    {
        super.deserialize_from_cdr_buffer(dst,buffer,length);
    }

    public Object deserialize_key_sample(
        Object endpoint_data,
        Object dst,
        CdrInputStream src,
        boolean deserialize_encapsulation,
        boolean deserialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_key) {

            DomainParticipantEntityStatistics typedDst = (DomainParticipantEntityStatistics) dst;

            while (end != true && src.available() > 0) {

                memberInfo = src.readMemberInfo();
                tmpPosition = src.getBuffer().currentPosition();
                tmpSize = src.getBuffer().getSize(); 
                tmpLength = memberInfo.length;
                src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));
                switch (memberInfo.memberId) {
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                    break; 
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                    end = true;
                    break;
                    case 0:
                    typedDst.participant_key = (DDSMonitoring.BuiltinTopicKey_t)DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().deserialize_key_sample(endpoint_data, typedDst.participant_key, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 1:
                    typedDst.period = (DDSMonitoring.Duration_t)DDSMonitoring.Duration_tTypeSupport.get_instance().deserialize_key_sample(endpoint_data, typedDst.period, src, false, true, endpoint_plugin_qos);     
                    break;
                    default:

                    if (memberInfo.flagMustUnderstand) {
                        throw new RETCODE_ERROR(
                            "unknown member ID "+ 
                            memberInfo.memberId);
                    } break;
                }
                src.getBuffer().setDesBufferSize(tmpSize);
                src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

            }

        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void skip(Object endpoint_data, 
    CdrInputStream src,
    boolean skip_encapsulation, 
    boolean skip_sample, 
    Object endpoint_plugin_qos)
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if (skip_encapsulation) {
            src.skipEncapsulation();

            position = src.resetAlignment();
        }

        if (skip_sample) {

            while (end != true && src.available() > 0) {

                memberInfo = src.readMemberInfo();
                tmpPosition = src.getBuffer().currentPosition();
                tmpSize = src.getBuffer().getSize(); 
                tmpLength = memberInfo.length;
                src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));
                switch (memberInfo.memberId) {
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                    break; 
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                    end = true;
                    break;
                    case 0:
                    DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 1:
                    DDSMonitoring.Duration_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 2:
                    src.skipInt();
                    break;

                    case 3:
                    src.skipInt();
                    break;

                    case 4:
                    src.skipInt();
                    break;

                    case 5:
                    rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 6:
                    src.skipInt();
                    break;

                    case 7:
                    src.skipInt();
                    break;

                    case 8:
                    src.skipInt();
                    break;

                    default:

                    if (memberInfo.flagMustUnderstand) {
                        throw new RETCODE_ERROR(
                            "unknown member ID "+ 
                            memberInfo.memberId);
                    } break;
                }        
                src.getBuffer().setDesBufferSize(tmpSize);
                src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

            }

        }

        if (skip_encapsulation) {
            src.restoreAlignment(position);
        }
    }

    public Object serialized_sample_to_key(
        Object endpoint_data,
        Object sample,
        CdrInputStream src, 
        boolean deserialize_encapsulation,  
        boolean deserialize_key, 
        Object endpoint_plugin_qos) 
    {

        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if (deserialize_key) {

            DomainParticipantEntityStatistics typedDst = (DomainParticipantEntityStatistics) sample;

            while (end != true && src.available() > 0) {

                memberInfo = src.readMemberInfo();
                tmpPosition = src.getBuffer().currentPosition();
                tmpSize = src.getBuffer().getSize(); 
                tmpLength = memberInfo.length;
                src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));
                switch (memberInfo.memberId) {
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                    break; 
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                    end = true;
                    break;

                    case 0:
                    typedDst.participant_key = (DDSMonitoring.BuiltinTopicKey_t)DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().serialized_sample_to_key(endpoint_data, typedDst.participant_key, src, false, true, endpoint_plugin_qos);     
                    break;

                    case 1:
                    typedDst.period = (DDSMonitoring.Duration_t)DDSMonitoring.Duration_tTypeSupport.get_instance().serialized_sample_to_key(endpoint_data, typedDst.period, src, false, true, endpoint_plugin_qos);     
                    break;

                    case 2:
                    src.skipInt();
                    break;

                    case 3:
                    src.skipInt();
                    break;

                    case 4:
                    src.skipInt();
                    break;

                    case 5:
                    rti.dds.monitoring.ProcessStatisticsTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 6:
                    src.skipInt();
                    break;

                    case 7:
                    src.skipInt();
                    break;

                    case 8:
                    src.skipInt();
                    break;
                    default:

                    if (memberInfo.flagMustUnderstand) {
                        throw new RETCODE_ERROR(
                            "unknown member ID "+ 
                            memberInfo.memberId);
                    } break;

                }

                src.getBuffer().setDesBufferSize(tmpSize);
                src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

            }

        }

        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return sample;
    }

    /* Fill in the key fields of the given instance sample based on the key.
    */
    public void key_to_instance(Object endpoint_data,
    Object instance,
    Object key) {
        DomainParticipantEntityStatistics typedDst
        = (DomainParticipantEntityStatistics) instance;
        DomainParticipantEntityStatistics typedSrc
        = (DomainParticipantEntityStatistics) key;
        typedDst.participant_key = (DDSMonitoring.BuiltinTopicKey_t) typedDst.participant_key.copy_from(typedSrc.participant_key);
        typedDst.period = (DDSMonitoring.Duration_t) typedDst.period.copy_from(typedSrc.period);

    }

    /* Fill in the given key based on the key fields of the given instance
    * sample.
    */
    public void instance_to_key(Object endpoint_data,
    Object key,
    Object instance) {
        DomainParticipantEntityStatistics typedDst
        = (DomainParticipantEntityStatistics)key;
        DomainParticipantEntityStatistics typedSrc
        = (DomainParticipantEntityStatistics) instance;
        typedDst.participant_key = (DDSMonitoring.BuiltinTopicKey_t) typedDst.participant_key.copy_from(typedSrc.participant_key);
        typedDst.period = (DDSMonitoring.Duration_t) typedDst.period.copy_from(typedSrc.period);

    }

    public void serialized_sample_to_keyhash(
        Object endpoint_data,
        CdrInputStream src,
        KeyHash_t keyhash,
        boolean include_encapsulation,
        Object endpoint_plugin_qos)
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        DefaultEndpointData endpointData = (DefaultEndpointData) endpoint_data;
        Object sample = null;

        sample = endpointData.get_sample();

        if (sample == null) {
            throw new RETCODE_ERROR("Missing intermediate sample");
        }

        DomainParticipantEntityStatistics typedDst = (DomainParticipantEntityStatistics) sample;

        if (include_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        while (end != true && src.available() > 0) {

            memberInfo = src.readMemberInfo();
            tmpPosition = src.getBuffer().currentPosition();
            tmpSize = src.getBuffer().getSize(); 
            tmpLength = memberInfo.length;
            src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));
            switch (memberInfo.memberId) {
                case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                break; 
                case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                end = true;
                break;

                case 0:
                typedDst.participant_key = (DDSMonitoring.BuiltinTopicKey_t)DDSMonitoring.BuiltinTopicKey_tTypeSupport.get_instance().serialized_sample_to_key(endpoint_data, typedDst.participant_key, src, false, true, endpoint_plugin_qos);     
                break;
                case 1:
                typedDst.period = (DDSMonitoring.Duration_t)DDSMonitoring.Duration_tTypeSupport.get_instance().serialized_sample_to_key(endpoint_data, typedDst.period, src, false, true, endpoint_plugin_qos);     
                break;
                default:

                if (memberInfo.flagMustUnderstand) {
                    throw new RETCODE_ERROR(
                        "unknown member ID "+ 
                        memberInfo.memberId);
                } break;
            }
            src.getBuffer().setDesBufferSize(tmpSize);
            src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

        }

        if (include_encapsulation) {
            src.restoreAlignment(position);
        }

        instance_to_keyhash(endpoint_data, keyhash, sample);
    }

    // -----------------------------------------------------------------------
    // Callbacks
    // -----------------------------------------------------------------------
    public Object on_participant_attached(Object registration_data,
    TypeSupportParticipantInfo participant_info,
    boolean top_level_registration,
    Object container_plugin_context,
    TypeCode type_code) {
        return super.on_participant_attached(
            registration_data, participant_info, top_level_registration,
            container_plugin_context, type_code);
    }

    public void on_participant_detached(Object participant_data) {
        super.on_participant_detached(participant_data);
    }

    public Object on_endpoint_attached(Object participantData,
    TypeSupportEndpointInfo endpoint_info,
    boolean top_level_registration,
    Object container_plugin_context) {
        return super.on_endpoint_attached(
            participantData,  endpoint_info,  
            top_level_registration, container_plugin_context);        
    }

    public void on_endpoint_detached(Object endpoint_data) {
        super.on_endpoint_detached(endpoint_data);
    }
    // -----------------------------------------------------------------------
    // Protected Methods
    // -----------------------------------------------------------------------

    protected DataWriter create_datawriter(long native_writer,
    DataWriterListener listener,
    int mask) {
        return new DomainParticipantEntityStatisticsDataWriter (native_writer, listener, mask, this);            
    }

    protected DataReader create_datareader(long native_reader,
    DataReaderListener listener,
    int mask) {

        return new DomainParticipantEntityStatisticsDataReader(native_reader, listener, mask, this);   

    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    protected DomainParticipantEntityStatisticsTypeSupport() {

        /* If the user data type supports keys, then the second argument
        to the constructor below should be true.  Otherwise it should
        be false. */        

        super(TYPE_NAME,true,DomainParticipantEntityStatisticsTypeCode.VALUE,DomainParticipantEntityStatistics.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);

    }

    protected DomainParticipantEntityStatisticsTypeSupport (boolean enableKeySupport) {

        super(TYPE_NAME, enableKeySupport,DomainParticipantEntityStatisticsTypeCode.VALUE,DomainParticipantEntityStatistics.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);
    }
}

