
/*
WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

This file was generated from .idl using "rtiddsgen".
The rtiddsgen tool is part of the RTI Connext distribution.
For more information, type 'rtiddsgen -help' at a command shell
or consult the RTI Connext manual.
*/

package DDSMonitoring;

import com.rti.dds.cdr.CdrEncapsulation;
import com.rti.dds.cdr.CdrInputStream;
import com.rti.dds.cdr.CdrOutputStream;
import com.rti.dds.cdr.CdrPrimitiveType;
import com.rti.dds.cdr.CdrBuffer;
import com.rti.dds.cdr.CdrHelper;
import com.rti.dds.cdr.CdrMemberInfo;
import com.rti.dds.domain.DomainParticipant;
import com.rti.dds.publication.DataWriter;
import com.rti.dds.publication.DataWriterListener;
import com.rti.dds.subscription.DataReader;
import com.rti.dds.subscription.DataReaderListener;
import com.rti.dds.topic.KeyHash_t;
import com.rti.dds.topic.TypeSupportImpl;
import com.rti.dds.topic.TypeSupportType;
import com.rti.dds.util.Sequence;
import com.rti.dds.topic.DefaultEndpointData;
import com.rti.dds.infrastructure.RETCODE_ERROR;

import com.rti.dds.infrastructure.*;
import com.rti.dds.topic.TypeSupportParticipantInfo;
import com.rti.dds.topic.TypeSupportEndpointInfo;
import com.rti.dds.typecode.TypeCode;
import com.rti.dds.cdr.IllegalCdrStateException;

import com.rti.dds.infrastructure.Copyable;

/**
* A collection of useful methods for dealing with objects of type
* DataReaderQos
*/

public class DataReaderQosTypeSupport extends TypeSupportImpl {
    // -----------------------------------------------------------------------
    // Private Fields
    // -----------------------------------------------------------------------

    private static final String TYPE_NAME = "DDSMonitoring::DataReaderQos";

    private static final char[] PLUGIN_VERSION = {2, 0, 0, 0};     
    private static final DataReaderQosTypeSupport _singleton
    = new DataReaderQosTypeSupport();

    // -----------------------------------------------------------------------
    // Public Methods
    // -----------------------------------------------------------------------

    // --- External methods: -------------------------------------------------
    /* The methods in this section are for use by users of RTI Connext
    */

    public static String get_type_name() {
        return _singleton.get_type_nameI();
    }

    public static void register_type(DomainParticipant participant,
    String type_name) {
        _singleton.register_typeI(participant, type_name);
    }

    public static void unregister_type(DomainParticipant participant,
    String type_name) {
        _singleton.unregister_typeI(participant, type_name);
    }

    /* The methods in this section are for use by RTI Connext
    * itself and by the code generated by rtiddsgen for other types.
    * They should be used directly or modified only by advanced users and are
    * subject to change in future versions of RTI Connext.
    */
    public static DataReaderQosTypeSupport get_instance() {
        return _singleton;
    }

    public static DataReaderQosTypeSupport getInstance() {
        return get_instance();
    }

    public static TypeCode getTypeCode(){
        return DataReaderQosTypeCode.VALUE;
    }

    public Object create_data() {
        return DataReaderQos.create();
    }

    public void destroy_data(Object data) {
        return;
    }
    public Object create_key() {
        return new DataReaderQos();
    }

    public void destroy_key(Object key) {
        return;
    }
    public Class get_type() {
        return DataReaderQos.class;
    }

    /**
    * This is a concrete implementation of this method inherited from the base class.
    * This method will perform a deep copy of <code>source</code> into
    * <code>destination</code>.
    * 
    * @param src The Object which contains the data to be copied.
    * @return Returns <code>destination</code>.
    * @exception NullPointerException If <code>destination</code> or 
    * <code>source</code> is null.
    * @exception ClassCastException If either <code>destination</code> or
    * <code>this</code> is not a <code>DataReaderQos</code>
    * type.
    */
    public Object copy_data(Object destination, Object source) {

        DataReaderQos typedDst = (DataReaderQos) destination;
        DataReaderQos typedSrc = (DataReaderQos) source;

        return typedDst.copy_from(typedSrc);

    }

    public long get_serialized_sample_max_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DurabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DeadlineQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.LatencyBudgetQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.LivelinessQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ReliabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DestinationOrderQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.HistoryQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ResourceLimitsQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.UserDataQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.OwnershipQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TimeBasedFilterQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ReaderDataLifecycleQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TypeConsistencyEnforcementQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DataReaderResourceLimitsQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DataReaderProtocolQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportSelectionQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportUnicastQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportMulticastQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportEncapsulationQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.PropertyQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ServiceQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.AvailabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.EntityNameQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportPriorityQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TypeSupportQosPolicyTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,0);
        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;
    }

    public long get_serialized_sample_min_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {

        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DurabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DeadlineQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.LatencyBudgetQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.LivelinessQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ReliabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DestinationOrderQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.HistoryQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ResourceLimitsQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.UserDataQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.OwnershipQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TimeBasedFilterQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ReaderDataLifecycleQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TypeConsistencyEnforcementQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DataReaderResourceLimitsQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DataReaderProtocolQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportSelectionQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportUnicastQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportMulticastQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportEncapsulationQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.PropertyQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ServiceQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.AvailabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.EntityNameQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportPriorityQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TypeSupportQosPolicyTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,0);

        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;

    }

    public long get_serialized_sample_size(
        Object endpoint_data, boolean include_encapsulation, 
        short encapsulation_id, long currentAlignment,
        Object sample) 
    {
        DataReaderQos typedSrc = (DataReaderQos) sample;
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DurabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.durability);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DeadlineQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.deadline);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.LatencyBudgetQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.latency_budget);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.LivelinessQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.liveliness);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ReliabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.reliability);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DestinationOrderQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.destination_order);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.HistoryQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.history);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ResourceLimitsQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.resource_limits);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.UserDataQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.user_data);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.OwnershipQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.ownership);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TimeBasedFilterQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.time_based_filter);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ReaderDataLifecycleQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.reader_data_lifecycle);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TypeConsistencyEnforcementQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.type_consistency);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DataReaderResourceLimitsQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.reader_resource_limits);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.DataReaderProtocolQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.protocol);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportSelectionQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.transport_selection);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportUnicastQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.unicast);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportMulticastQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.multicast);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportEncapsulationQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.encapsulation);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.PropertyQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.property);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.ServiceQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.service);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.AvailabilityQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.availability);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.EntityNameQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.subscription_name);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TransportPriorityQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.transport_priority);
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 12);
        currentAlignment += DDSMonitoring.TypeSupportQosPolicyTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,0,typedSrc.type_support);
        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) + 4);

        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return currentAlignment - origAlignment;
    }

    public long get_serialized_key_max_size(
        Object endpoint_data,
        boolean include_encapsulation, 
        short encapsulation_id,
        long currentAlignment) 
    {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += get_serialized_sample_max_size(
            endpoint_data,false,encapsulation_id,currentAlignment);
        // Sentinel
        currentAlignment += (CdrPrimitiveType.getPadSize(currentAlignment, 4) +
        2*CdrPrimitiveType.SHORT.size +
        2*CdrPrimitiveType.INT.size);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }

        return currentAlignment - origAlignment;
    }

    public void serialize(Object endpoint_data,Object src, CdrOutputStream dst,boolean serialize_encapsulation,
    short encapsulation_id, boolean serialize_sample, Object endpoint_plugin_qos) {
        int position = 0;
        long memberId = 0;
        int memberLengthPosition = 0;
        boolean skipListEndId_tmp = false;
        long maxLength = 0;

        if (!dst.isDirty()) {
            dst.setDirtyBit(true);

            try{
                maxLength = get_serialized_sample_max_size(endpoint_data, false, encapsulation_id,0);
            } catch (ArithmeticException ex) {
                maxLength =  MAX_SAMPLE_SIZE;
            }

            if (maxLength > 65535) {
                dst.useExtendedMemberId = true;
            }
            else{
                dst.useExtendedMemberId = false;
            }
        }

        skipListEndId_tmp =  dst.skipListEndId;
        dst.skipListEndId = false;

        if(serialize_encapsulation) {
            if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_BE;
            } else if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_LE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_LE;
            }

            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();

        }

        if(serialize_sample) {

            DataReaderQos typedSrc = (DataReaderQos) src;

            memberId = 0;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.DurabilityQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.durability, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 1;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.DeadlineQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.deadline, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 2;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.LatencyBudgetQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.latency_budget, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 3;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.LivelinessQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.liveliness, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 4;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.ReliabilityQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.reliability, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 5;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.DestinationOrderQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.destination_order, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 6;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.HistoryQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.history, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 7;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.ResourceLimitsQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.resource_limits, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 8;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.UserDataQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.user_data, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 9;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.OwnershipQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.ownership, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 10;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TimeBasedFilterQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.time_based_filter, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 11;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.ReaderDataLifecycleQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.reader_data_lifecycle, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 12;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TypeConsistencyEnforcementQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.type_consistency, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 13;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.DataReaderResourceLimitsQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.reader_resource_limits, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 14;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.DataReaderProtocolQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.protocol, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 15;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TransportSelectionQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.transport_selection, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 16;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TransportUnicastQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.unicast, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 17;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TransportMulticastQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.multicast, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 18;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TransportEncapsulationQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.encapsulation, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 19;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.PropertyQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.property, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 20;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.ServiceQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.service, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 21;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.AvailabilityQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.availability, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 22;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.EntityNameQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.subscription_name, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 24;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TransportPriorityQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.transport_priority, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }

            memberId = 23;
            if (dst.useExtendedMemberId == true) {
                memberLengthPosition = dst.writeMemberId((int)memberId);
            } else {
                memberLengthPosition = dst.writeMemberId((short)memberId);
            }
            DDSMonitoring.TypeSupportQosPolicyTypeSupport.get_instance().serialize(endpoint_data, typedSrc.type_support, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            if (dst.useExtendedMemberId == true) {
                dst.writeMemberLength(memberLengthPosition, true);
            } else {
                dst.writeMemberLength(memberLengthPosition, false);
            }
            if (!(skipListEndId_tmp)) {
                boolean mustUnderstand=false; /*Not default. Explicity set for backward compatibility*/
                memberLengthPosition = 
                dst.writeMemberId(
                    (short)CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END, mustUnderstand);
                dst.writeMemberLength(memberLengthPosition, false);
            }
            dst.skipListEndId = skipListEndId_tmp;

        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }

    }
    public long serialize_to_cdr_buffer(
        byte[] buffer,
        long length,
        DataReaderQos src)
    {
        return super.serialize_to_cdr_buffer(buffer,length,src);
    }

    public void serialize_key(
        Object endpoint_data,
        Object src,
        CdrOutputStream dst,
        boolean serialize_encapsulation,
        short encapsulation_id,
        boolean serialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        boolean skipListEndId_tmp = false;
        long maxLength = 0;

        if (!dst.isDirty()) {
            dst.setDirtyBit(true);

            try{
                maxLength = get_serialized_sample_max_size(endpoint_data, false, encapsulation_id,0);
            } catch (ArithmeticException ex) {
                maxLength =  MAX_SAMPLE_SIZE;
            }

            if (maxLength > 65535) {
                dst.useExtendedMemberId = true;
            }
            else{
                dst.useExtendedMemberId = false;
            }
        }

        skipListEndId_tmp =  dst.skipListEndId;
        dst.skipListEndId = false;

        if (serialize_encapsulation) {
            if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_BE;
            } else if (encapsulation_id == CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_LE) {
                encapsulation_id = CdrEncapsulation.CDR_ENCAPSULATION_ID_PL_CDR_LE;
            }

            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();
        }

        if (serialize_key) {

            DataReaderQos typedSrc = (DataReaderQos) src;    
            dst.skipListEndId = false;
            serialize(endpoint_data, src, dst, false, CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE, true, endpoint_plugin_qos);

        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }
    }

    public Object deserialize_sample(
        Object endpoint_data,
        Object dst, 
        CdrInputStream src, boolean deserialize_encapsulation,
        boolean deserialize_sample,
        Object endpoint_plugin_qos) 
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_sample) {

            DataReaderQos typedDst = (DataReaderQos) dst;
            typedDst.clear();      
            while (end != true && src.available() > 0) {

                memberInfo = src.readMemberInfo();
                tmpPosition = src.getBuffer().currentPosition();
                tmpSize = src.getBuffer().getSize(); 
                tmpLength = memberInfo.length;
                src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));

                switch (memberInfo.memberId) {

                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                    break; 

                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                    end = true;
                    break;
                    case 0:
                    typedDst.durability = (DDSMonitoring.DurabilityQosPolicy)DDSMonitoring.DurabilityQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.durability, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 1:
                    typedDst.deadline = (DDSMonitoring.DeadlineQosPolicy)DDSMonitoring.DeadlineQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.deadline, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 2:
                    typedDst.latency_budget = (DDSMonitoring.LatencyBudgetQosPolicy)DDSMonitoring.LatencyBudgetQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.latency_budget, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 3:
                    typedDst.liveliness = (DDSMonitoring.LivelinessQosPolicy)DDSMonitoring.LivelinessQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.liveliness, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 4:
                    typedDst.reliability = (DDSMonitoring.ReliabilityQosPolicy)DDSMonitoring.ReliabilityQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.reliability, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 5:
                    typedDst.destination_order = (DDSMonitoring.DestinationOrderQosPolicy)DDSMonitoring.DestinationOrderQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.destination_order, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 6:
                    typedDst.history = (DDSMonitoring.HistoryQosPolicy)DDSMonitoring.HistoryQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.history, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 7:
                    typedDst.resource_limits = (DDSMonitoring.ResourceLimitsQosPolicy)DDSMonitoring.ResourceLimitsQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.resource_limits, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 8:
                    typedDst.user_data = (DDSMonitoring.UserDataQosPolicy)DDSMonitoring.UserDataQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.user_data, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 9:
                    typedDst.ownership = (DDSMonitoring.OwnershipQosPolicy)DDSMonitoring.OwnershipQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.ownership, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 10:
                    typedDst.time_based_filter = (DDSMonitoring.TimeBasedFilterQosPolicy)DDSMonitoring.TimeBasedFilterQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.time_based_filter, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 11:
                    typedDst.reader_data_lifecycle = (DDSMonitoring.ReaderDataLifecycleQosPolicy)DDSMonitoring.ReaderDataLifecycleQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.reader_data_lifecycle, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 12:
                    typedDst.type_consistency = (DDSMonitoring.TypeConsistencyEnforcementQosPolicy)DDSMonitoring.TypeConsistencyEnforcementQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.type_consistency, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 13:
                    typedDst.reader_resource_limits = (DDSMonitoring.DataReaderResourceLimitsQosPolicy)DDSMonitoring.DataReaderResourceLimitsQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.reader_resource_limits, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 14:
                    typedDst.protocol = (DDSMonitoring.DataReaderProtocolQosPolicy)DDSMonitoring.DataReaderProtocolQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.protocol, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 15:
                    typedDst.transport_selection = (DDSMonitoring.TransportSelectionQosPolicy)DDSMonitoring.TransportSelectionQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.transport_selection, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 16:
                    typedDst.unicast = (DDSMonitoring.TransportUnicastQosPolicy)DDSMonitoring.TransportUnicastQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.unicast, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 17:
                    typedDst.multicast = (DDSMonitoring.TransportMulticastQosPolicy)DDSMonitoring.TransportMulticastQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.multicast, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 18:
                    typedDst.encapsulation = (DDSMonitoring.TransportEncapsulationQosPolicy)DDSMonitoring.TransportEncapsulationQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.encapsulation, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 19:
                    typedDst.property = (DDSMonitoring.PropertyQosPolicy)DDSMonitoring.PropertyQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.property, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 20:
                    typedDst.service = (DDSMonitoring.ServiceQosPolicy)DDSMonitoring.ServiceQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.service, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 21:
                    typedDst.availability = (DDSMonitoring.AvailabilityQosPolicy)DDSMonitoring.AvailabilityQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.availability, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 22:
                    typedDst.subscription_name = (DDSMonitoring.EntityNameQosPolicy)DDSMonitoring.EntityNameQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.subscription_name, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 24:
                    typedDst.transport_priority = (DDSMonitoring.TransportPriorityQosPolicy)DDSMonitoring.TransportPriorityQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.transport_priority, src, false, true, endpoint_plugin_qos);     
                    break;
                    case 23:
                    typedDst.type_support = (DDSMonitoring.TypeSupportQosPolicy)DDSMonitoring.TypeSupportQosPolicyTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.type_support, src, false, true, endpoint_plugin_qos);     
                    break;
                    default:
                    if (memberInfo.flagMustUnderstand) {
                        throw new RETCODE_ERROR(
                            "unknown member ID "+ 
                            memberInfo.memberId);
                    } break;
                }             
                src.getBuffer().setDesBufferSize(tmpSize);
                src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

            }
        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void deserialize_from_cdr_buffer(
        DataReaderQos dst,
        byte[] buffer,
        long length) 
    {
        super.deserialize_from_cdr_buffer(dst,buffer,length);
    }

    public Object deserialize_key_sample(
        Object endpoint_data,
        Object dst,
        CdrInputStream src,
        boolean deserialize_encapsulation,
        boolean deserialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_key) {

            DataReaderQos typedDst = (DataReaderQos) dst;

            deserialize_sample(endpoint_data, dst, src, false, true, endpoint_plugin_qos);

        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void skip(Object endpoint_data, 
    CdrInputStream src,
    boolean skip_encapsulation, 
    boolean skip_sample, 
    Object endpoint_plugin_qos)
    {
        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if (skip_encapsulation) {
            src.skipEncapsulation();

            position = src.resetAlignment();
        }

        if (skip_sample) {

            while (end != true && src.available() > 0) {

                memberInfo = src.readMemberInfo();
                tmpPosition = src.getBuffer().currentPosition();
                tmpSize = src.getBuffer().getSize(); 
                tmpLength = memberInfo.length;
                src.getBuffer().setDesBufferSize((int)(tmpPosition + memberInfo.length));
                switch (memberInfo.memberId) {
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_IGNORE:
                    break; 
                    case CdrEncapsulation.CDR_ENCAPSULATION_MEMBER_ID_LIST_END: 
                    end = true;
                    break;
                    case 0:
                    DDSMonitoring.DurabilityQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 1:
                    DDSMonitoring.DeadlineQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 2:
                    DDSMonitoring.LatencyBudgetQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 3:
                    DDSMonitoring.LivelinessQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 4:
                    DDSMonitoring.ReliabilityQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 5:
                    DDSMonitoring.DestinationOrderQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 6:
                    DDSMonitoring.HistoryQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 7:
                    DDSMonitoring.ResourceLimitsQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 8:
                    DDSMonitoring.UserDataQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 9:
                    DDSMonitoring.OwnershipQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 10:
                    DDSMonitoring.TimeBasedFilterQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 11:
                    DDSMonitoring.ReaderDataLifecycleQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 12:
                    DDSMonitoring.TypeConsistencyEnforcementQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 13:
                    DDSMonitoring.DataReaderResourceLimitsQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 14:
                    DDSMonitoring.DataReaderProtocolQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 15:
                    DDSMonitoring.TransportSelectionQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 16:
                    DDSMonitoring.TransportUnicastQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 17:
                    DDSMonitoring.TransportMulticastQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 18:
                    DDSMonitoring.TransportEncapsulationQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 19:
                    DDSMonitoring.PropertyQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 20:
                    DDSMonitoring.ServiceQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 21:
                    DDSMonitoring.AvailabilityQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 22:
                    DDSMonitoring.EntityNameQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 24:
                    DDSMonitoring.TransportPriorityQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    case 23:
                    DDSMonitoring.TypeSupportQosPolicyTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);
                    break;

                    default:

                    if (memberInfo.flagMustUnderstand) {
                        throw new RETCODE_ERROR(
                            "unknown member ID "+ 
                            memberInfo.memberId);
                    } break;
                }        
                src.getBuffer().setDesBufferSize(tmpSize);
                src.getBuffer().setCurrentPosition((int)(tmpPosition + tmpLength));

            }

        }

        if (skip_encapsulation) {
            src.restoreAlignment(position);
        }
    }

    public Object serialized_sample_to_key(
        Object endpoint_data,
        Object sample,
        CdrInputStream src, 
        boolean deserialize_encapsulation,  
        boolean deserialize_key, 
        Object endpoint_plugin_qos) 
    {

        int position = 0;
        CdrMemberInfo memberInfo;
        long length = 0;
        boolean end = false;
        int tmpPosition, tmpSize;
        long tmpLength;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if (deserialize_key) {

            DataReaderQos typedDst = (DataReaderQos) sample;

            deserialize_sample(
                endpoint_data, sample, src, false,
                true, endpoint_plugin_qos);

        }

        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return sample;
    }

    // -----------------------------------------------------------------------
    // Callbacks
    // -----------------------------------------------------------------------
    public Object on_participant_attached(Object registration_data,
    TypeSupportParticipantInfo participant_info,
    boolean top_level_registration,
    Object container_plugin_context,
    TypeCode type_code) {
        return super.on_participant_attached(
            registration_data, participant_info, top_level_registration,
            container_plugin_context, type_code);
    }

    public void on_participant_detached(Object participant_data) {
        super.on_participant_detached(participant_data);
    }

    public Object on_endpoint_attached(Object participantData,
    TypeSupportEndpointInfo endpoint_info,
    boolean top_level_registration,
    Object container_plugin_context) {
        return super.on_endpoint_attached(
            participantData,  endpoint_info,  
            top_level_registration, container_plugin_context);        
    }

    public void on_endpoint_detached(Object endpoint_data) {
        super.on_endpoint_detached(endpoint_data);
    }
    // -----------------------------------------------------------------------
    // Protected Methods
    // -----------------------------------------------------------------------

    protected DataWriter create_datawriter(long native_writer,
    DataWriterListener listener,
    int mask) {
        return null;

    }

    protected DataReader create_datareader(long native_reader,
    DataReaderListener listener,
    int mask) {

        return null;

    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    protected DataReaderQosTypeSupport() {

        /* If the user data type supports keys, then the second argument
        to the constructor below should be true.  Otherwise it should
        be false. */        

        super(TYPE_NAME, false,DataReaderQosTypeCode.VALUE,DataReaderQos.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);

    }

    protected DataReaderQosTypeSupport (boolean enableKeySupport) {

        super(TYPE_NAME, enableKeySupport,DataReaderQosTypeCode.VALUE,DataReaderQos.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);
    }
}

