
/*
WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

This file was generated from .idl using "rtiddsgen".
The rtiddsgen tool is part of the RTI Connext distribution.
For more information, type 'rtiddsgen -help' at a command shell
or consult the RTI Connext manual.
*/

package DDSMonitoring;

import com.rti.dds.cdr.CdrEncapsulation;
import com.rti.dds.cdr.CdrInputStream;
import com.rti.dds.cdr.CdrOutputStream;
import com.rti.dds.cdr.CdrPrimitiveType;
import com.rti.dds.cdr.CdrBuffer;
import com.rti.dds.cdr.CdrHelper;
import com.rti.dds.cdr.CdrMemberInfo;
import com.rti.dds.domain.DomainParticipant;
import com.rti.dds.publication.DataWriter;
import com.rti.dds.publication.DataWriterListener;
import com.rti.dds.subscription.DataReader;
import com.rti.dds.subscription.DataReaderListener;
import com.rti.dds.topic.KeyHash_t;
import com.rti.dds.topic.TypeSupportImpl;
import com.rti.dds.topic.TypeSupportType;
import com.rti.dds.util.Sequence;
import com.rti.dds.topic.DefaultEndpointData;
import com.rti.dds.infrastructure.RETCODE_ERROR;

import com.rti.dds.infrastructure.*;
import com.rti.dds.topic.TypeSupportParticipantInfo;
import com.rti.dds.topic.TypeSupportEndpointInfo;
import com.rti.dds.typecode.TypeCode;
import com.rti.dds.cdr.IllegalCdrStateException;

import com.rti.dds.infrastructure.Copyable;

/**
* A collection of useful methods for dealing with objects of type
* DomainParticipantResourceLimitsQosPolicy
*/

public class DomainParticipantResourceLimitsQosPolicyTypeSupport extends TypeSupportImpl {
    // -----------------------------------------------------------------------
    // Private Fields
    // -----------------------------------------------------------------------

    private static final String TYPE_NAME = "DDSMonitoring::DomainParticipantResourceLimitsQosPolicy";

    private static final char[] PLUGIN_VERSION = {2, 0, 0, 0};     
    private static final DomainParticipantResourceLimitsQosPolicyTypeSupport _singleton
    = new DomainParticipantResourceLimitsQosPolicyTypeSupport();

    // -----------------------------------------------------------------------
    // Public Methods
    // -----------------------------------------------------------------------

    // --- External methods: -------------------------------------------------
    /* The methods in this section are for use by users of RTI Connext
    */

    public static String get_type_name() {
        return _singleton.get_type_nameI();
    }

    public static void register_type(DomainParticipant participant,
    String type_name) {
        _singleton.register_typeI(participant, type_name);
    }

    public static void unregister_type(DomainParticipant participant,
    String type_name) {
        _singleton.unregister_typeI(participant, type_name);
    }

    /* The methods in this section are for use by RTI Connext
    * itself and by the code generated by rtiddsgen for other types.
    * They should be used directly or modified only by advanced users and are
    * subject to change in future versions of RTI Connext.
    */
    public static DomainParticipantResourceLimitsQosPolicyTypeSupport get_instance() {
        return _singleton;
    }

    public static DomainParticipantResourceLimitsQosPolicyTypeSupport getInstance() {
        return get_instance();
    }

    public static TypeCode getTypeCode(){
        return DomainParticipantResourceLimitsQosPolicyTypeCode.VALUE;
    }

    public Object create_data() {
        return DomainParticipantResourceLimitsQosPolicy.create();
    }

    public void destroy_data(Object data) {
        return;
    }
    public Object create_key() {
        return new DomainParticipantResourceLimitsQosPolicy();
    }

    public void destroy_key(Object key) {
        return;
    }
    public Class get_type() {
        return DomainParticipantResourceLimitsQosPolicy.class;
    }

    /**
    * This is a concrete implementation of this method inherited from the base class.
    * This method will perform a deep copy of <code>source</code> into
    * <code>destination</code>.
    * 
    * @param src The Object which contains the data to be copied.
    * @return Returns <code>destination</code>.
    * @exception NullPointerException If <code>destination</code> or 
    * <code>source</code> is null.
    * @exception ClassCastException If either <code>destination</code> or
    * <code>this</code> is not a <code>DomainParticipantResourceLimitsQosPolicy</code>
    * type.
    */
    public Object copy_data(Object destination, Object source) {

        DomainParticipantResourceLimitsQosPolicy typedDst = (DomainParticipantResourceLimitsQosPolicy) destination;
        DomainParticipantResourceLimitsQosPolicy typedSrc = (DomainParticipantResourceLimitsQosPolicy) source;

        return typedDst.copy_from(typedSrc);

    }

    public long get_serialized_sample_max_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKindTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;
    }

    public long get_serialized_sample_min_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {

        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        currentAlignment += DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKindTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);

        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;

    }

    public long get_serialized_sample_size(
        Object endpoint_data, boolean include_encapsulation, 
        short encapsulation_id, long currentAlignment,
        Object sample) 
    {
        DomainParticipantResourceLimitsQosPolicy typedSrc = (DomainParticipantResourceLimitsQosPolicy) sample;
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.local_writer_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.local_reader_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.local_publisher_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.local_subscriber_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.local_topic_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.remote_writer_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.remote_reader_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.remote_participant_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.matching_writer_reader_pair_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.matching_reader_writer_pair_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.ignored_entity_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.content_filtered_topic_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.content_filter_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.read_condition_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.query_condition_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.outstanding_asynchronous_sample_allocation);
        currentAlignment += DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.flow_controller_allocation);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        currentAlignment += DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKindTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.ignored_entity_replacement_kind);

        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return currentAlignment - origAlignment;
    }

    public long get_serialized_key_max_size(
        Object endpoint_data,
        boolean include_encapsulation, 
        short encapsulation_id,
        long currentAlignment) 
    {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += get_serialized_sample_max_size(
            endpoint_data,false,encapsulation_id,currentAlignment);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }

        return currentAlignment - origAlignment;
    }

    public void serialize(Object endpoint_data,Object src, CdrOutputStream dst,boolean serialize_encapsulation,
    short encapsulation_id, boolean serialize_sample, Object endpoint_plugin_qos) {
        int position = 0;

        if(serialize_encapsulation) {
            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();

        }

        if(serialize_sample) {

            DomainParticipantResourceLimitsQosPolicy typedSrc = (DomainParticipantResourceLimitsQosPolicy) src;

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.local_writer_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.local_reader_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.local_publisher_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.local_subscriber_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.local_topic_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.remote_writer_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.remote_reader_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.remote_participant_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.matching_writer_reader_pair_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.matching_reader_writer_pair_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.ignored_entity_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.content_filtered_topic_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.content_filter_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.read_condition_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.query_condition_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.outstanding_asynchronous_sample_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().serialize(endpoint_data, typedSrc.flow_controller_allocation, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            dst.writeInt(typedSrc.local_writer_hash_buckets);

            dst.writeInt(typedSrc.local_reader_hash_buckets);

            dst.writeInt(typedSrc.local_publisher_hash_buckets);

            dst.writeInt(typedSrc.local_subscriber_hash_buckets);

            dst.writeInt(typedSrc.local_topic_hash_buckets);

            dst.writeInt(typedSrc.remote_writer_hash_buckets);

            dst.writeInt(typedSrc.remote_reader_hash_buckets);

            dst.writeInt(typedSrc.remote_participant_hash_buckets);

            dst.writeInt(typedSrc.matching_writer_reader_pair_hash_buckets);

            dst.writeInt(typedSrc.matching_reader_writer_pair_hash_buckets);

            dst.writeInt(typedSrc.ignored_entity_hash_buckets);

            dst.writeInt(typedSrc.content_filtered_topic_hash_buckets);

            dst.writeInt(typedSrc.content_filter_hash_buckets);

            dst.writeInt(typedSrc.flow_controller_hash_buckets);

            dst.writeInt(typedSrc.max_gather_destinations);

            dst.writeInt(typedSrc.participant_user_data_max_length);

            dst.writeInt(typedSrc.inter_participant_data_max_length);

            dst.writeInt(typedSrc.topic_data_max_length);

            dst.writeInt(typedSrc.publisher_group_data_max_length);

            dst.writeInt(typedSrc.subscriber_group_data_max_length);

            dst.writeInt(typedSrc.writer_user_data_max_length);

            dst.writeInt(typedSrc.reader_user_data_max_length);

            dst.writeInt(typedSrc.max_partitions);

            dst.writeInt(typedSrc.max_partition_cumulative_characters);

            dst.writeBoolean(typedSrc.default_partition_matches_all);

            dst.writeBoolean(typedSrc.allow_no_partitions);

            dst.writeInt(typedSrc.type_code_max_serialized_length);

            dst.writeInt(typedSrc.type_object_max_serialized_length);

            dst.writeInt(typedSrc.serialized_type_object_dynamic_allocation_threshold);

            dst.writeInt(typedSrc.type_object_max_deserialized_length);

            dst.writeInt(typedSrc.deserialized_type_object_dynamic_allocation_threshold);

            dst.writeInt(typedSrc.contentfilter_property_max_length);

            dst.writeInt(typedSrc.channel_seq_max_length);

            dst.writeInt(typedSrc.channel_filter_expression_max_length);

            dst.writeInt(typedSrc.participant_property_list_max_length);

            dst.writeInt(typedSrc.participant_property_string_max_length);

            dst.writeInt(typedSrc.writer_property_list_max_length);

            dst.writeInt(typedSrc.writer_property_string_max_length);

            dst.writeInt(typedSrc.reader_property_list_max_length);

            dst.writeInt(typedSrc.reader_property_string_max_length);

            dst.writeInt(typedSrc.plugin_info_parameter_max_length);

            dst.writeInt(typedSrc.max_endpoint_groups);

            dst.writeInt(typedSrc.max_endpoint_group_cumulative_characters);

            dst.writeInt(typedSrc.transport_info_list_max_length);

            DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKindTypeSupport.get_instance().serialize(endpoint_data, typedSrc.ignored_entity_replacement_kind, dst, false, encapsulation_id,true,endpoint_plugin_qos);
        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }

    }
    public long serialize_to_cdr_buffer(
        byte[] buffer,
        long length,
        DomainParticipantResourceLimitsQosPolicy src)
    {
        return super.serialize_to_cdr_buffer(buffer,length,src);
    }

    public void serialize_key(
        Object endpoint_data,
        Object src,
        CdrOutputStream dst,
        boolean serialize_encapsulation,
        short encapsulation_id,
        boolean serialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        if (serialize_encapsulation) {
            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();
        }

        if (serialize_key) {

            DomainParticipantResourceLimitsQosPolicy typedSrc = (DomainParticipantResourceLimitsQosPolicy) src;    
            serialize(endpoint_data, src, dst, false, CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE, true, endpoint_plugin_qos);

        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }
    }

    public Object deserialize_sample(
        Object endpoint_data,
        Object dst, 
        CdrInputStream src, boolean deserialize_encapsulation,
        boolean deserialize_sample,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_sample) {

            DomainParticipantResourceLimitsQosPolicy typedDst = (DomainParticipantResourceLimitsQosPolicy) dst;
            typedDst.clear();      
            try{
                typedDst.local_writer_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.local_writer_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.local_reader_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.local_reader_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.local_publisher_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.local_publisher_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.local_subscriber_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.local_subscriber_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.local_topic_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.local_topic_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.remote_writer_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.remote_writer_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.remote_reader_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.remote_reader_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.remote_participant_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.remote_participant_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.matching_writer_reader_pair_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.matching_writer_reader_pair_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.matching_reader_writer_pair_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.matching_reader_writer_pair_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.ignored_entity_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.ignored_entity_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.content_filtered_topic_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.content_filtered_topic_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.content_filter_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.content_filter_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.read_condition_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.read_condition_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.query_condition_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.query_condition_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.outstanding_asynchronous_sample_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.outstanding_asynchronous_sample_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.flow_controller_allocation = (DDSMonitoring.AllocationSettings_t)DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.flow_controller_allocation, src, false, true, endpoint_plugin_qos);     
                typedDst.local_writer_hash_buckets = src.readInt();
                typedDst.local_reader_hash_buckets = src.readInt();
                typedDst.local_publisher_hash_buckets = src.readInt();
                typedDst.local_subscriber_hash_buckets = src.readInt();
                typedDst.local_topic_hash_buckets = src.readInt();
                typedDst.remote_writer_hash_buckets = src.readInt();
                typedDst.remote_reader_hash_buckets = src.readInt();
                typedDst.remote_participant_hash_buckets = src.readInt();
                typedDst.matching_writer_reader_pair_hash_buckets = src.readInt();
                typedDst.matching_reader_writer_pair_hash_buckets = src.readInt();
                typedDst.ignored_entity_hash_buckets = src.readInt();
                typedDst.content_filtered_topic_hash_buckets = src.readInt();
                typedDst.content_filter_hash_buckets = src.readInt();
                typedDst.flow_controller_hash_buckets = src.readInt();
                typedDst.max_gather_destinations = src.readInt();
                typedDst.participant_user_data_max_length = src.readInt();
                typedDst.inter_participant_data_max_length = src.readInt();
                typedDst.topic_data_max_length = src.readInt();
                typedDst.publisher_group_data_max_length = src.readInt();
                typedDst.subscriber_group_data_max_length = src.readInt();
                typedDst.writer_user_data_max_length = src.readInt();
                typedDst.reader_user_data_max_length = src.readInt();
                typedDst.max_partitions = src.readInt();
                typedDst.max_partition_cumulative_characters = src.readInt();
                typedDst.default_partition_matches_all = src.readBoolean();
                typedDst.allow_no_partitions = src.readBoolean();
                typedDst.type_code_max_serialized_length = src.readInt();
                typedDst.type_object_max_serialized_length = src.readInt();
                typedDst.serialized_type_object_dynamic_allocation_threshold = src.readInt();
                typedDst.type_object_max_deserialized_length = src.readInt();
                typedDst.deserialized_type_object_dynamic_allocation_threshold = src.readInt();
                typedDst.contentfilter_property_max_length = src.readInt();
                typedDst.channel_seq_max_length = src.readInt();
                typedDst.channel_filter_expression_max_length = src.readInt();
                typedDst.participant_property_list_max_length = src.readInt();
                typedDst.participant_property_string_max_length = src.readInt();
                typedDst.writer_property_list_max_length = src.readInt();
                typedDst.writer_property_string_max_length = src.readInt();
                typedDst.reader_property_list_max_length = src.readInt();
                typedDst.reader_property_string_max_length = src.readInt();
                typedDst.plugin_info_parameter_max_length = src.readInt();
                typedDst.max_endpoint_groups = src.readInt();
                typedDst.max_endpoint_group_cumulative_characters = src.readInt();
                typedDst.transport_info_list_max_length = src.readInt();
                typedDst.ignored_entity_replacement_kind = (DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKind)DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKindTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.ignored_entity_replacement_kind, src, false, true, endpoint_plugin_qos);     
            } catch (IllegalCdrStateException stateEx) {
                if (src.available() >= CdrEncapsulation.CDR_ENCAPSULATION_PARAMETER_ID_ALIGNMENT) {
                    throw new RETCODE_ERROR("Error deserializing sample! Remainder: " + src.available() + "\n" +
                    "Exception caused by: " + stateEx.getMessage());
                }
            } catch (Exception ex) {
                throw new RETCODE_ERROR(ex.getMessage());        
            }

        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void deserialize_from_cdr_buffer(
        DomainParticipantResourceLimitsQosPolicy dst,
        byte[] buffer,
        long length) 
    {
        super.deserialize_from_cdr_buffer(dst,buffer,length);
    }

    public Object deserialize_key_sample(
        Object endpoint_data,
        Object dst,
        CdrInputStream src,
        boolean deserialize_encapsulation,
        boolean deserialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_key) {

            DomainParticipantResourceLimitsQosPolicy typedDst = (DomainParticipantResourceLimitsQosPolicy) dst;

            deserialize_sample(endpoint_data, dst, src, false, true, endpoint_plugin_qos);

        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void skip(Object endpoint_data, 
    CdrInputStream src,
    boolean skip_encapsulation, 
    boolean skip_sample, 
    Object endpoint_plugin_qos)
    {
        int position = 0;

        if (skip_encapsulation) {
            src.skipEncapsulation();

            position = src.resetAlignment();
        }

        if (skip_sample) {

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            DDSMonitoring.AllocationSettings_tTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipBoolean();

            src.skipBoolean();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            src.skipInt();

            DDSMonitoring.DomainParticipantResourceLimitsIgnoredEntityReplacementKindTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

        }

        if (skip_encapsulation) {
            src.restoreAlignment(position);
        }
    }

    public Object serialized_sample_to_key(
        Object endpoint_data,
        Object sample,
        CdrInputStream src, 
        boolean deserialize_encapsulation,  
        boolean deserialize_key, 
        Object endpoint_plugin_qos) 
    {

        int position = 0;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if (deserialize_key) {

            DomainParticipantResourceLimitsQosPolicy typedDst = (DomainParticipantResourceLimitsQosPolicy) sample;

            deserialize_sample(
                endpoint_data, sample, src, false,
                true, endpoint_plugin_qos);

        }

        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return sample;
    }

    // -----------------------------------------------------------------------
    // Callbacks
    // -----------------------------------------------------------------------
    public Object on_participant_attached(Object registration_data,
    TypeSupportParticipantInfo participant_info,
    boolean top_level_registration,
    Object container_plugin_context,
    TypeCode type_code) {
        return super.on_participant_attached(
            registration_data, participant_info, top_level_registration,
            container_plugin_context, type_code);
    }

    public void on_participant_detached(Object participant_data) {
        super.on_participant_detached(participant_data);
    }

    public Object on_endpoint_attached(Object participantData,
    TypeSupportEndpointInfo endpoint_info,
    boolean top_level_registration,
    Object container_plugin_context) {
        return super.on_endpoint_attached(
            participantData,  endpoint_info,  
            top_level_registration, container_plugin_context);        
    }

    public void on_endpoint_detached(Object endpoint_data) {
        super.on_endpoint_detached(endpoint_data);
    }
    // -----------------------------------------------------------------------
    // Protected Methods
    // -----------------------------------------------------------------------

    protected DataWriter create_datawriter(long native_writer,
    DataWriterListener listener,
    int mask) {
        return null;

    }

    protected DataReader create_datareader(long native_reader,
    DataReaderListener listener,
    int mask) {

        return null;

    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    protected DomainParticipantResourceLimitsQosPolicyTypeSupport() {

        /* If the user data type supports keys, then the second argument
        to the constructor below should be true.  Otherwise it should
        be false. */        

        super(TYPE_NAME, false,DomainParticipantResourceLimitsQosPolicyTypeCode.VALUE,DomainParticipantResourceLimitsQosPolicy.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);

    }

    protected DomainParticipantResourceLimitsQosPolicyTypeSupport (boolean enableKeySupport) {

        super(TYPE_NAME, enableKeySupport,DomainParticipantResourceLimitsQosPolicyTypeCode.VALUE,DomainParticipantResourceLimitsQosPolicy.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);
    }
}

